### PR TITLE
support parameter overwrite without json

### PR DESCRIPTION
**Pull request by JackSlateur**
Hello @Sonic0 

We had another need recently
In our use case, the events must be sent to splunk in a specific (and ugly) format: we cannot send them as json
However, we'd like to overwrite splunk parameters, especially `time`

So far, parameter overrides is only supported with json

I've implemented one approach in this merge request: the user can supply a callback function and then call send_data() with dicts. The callback function is in charge of transforming events into whatever format is required. It is called after the parameters override.

One other approach would be to rework the send_data() method, which would take one event (in textual format, for instance) and some optional parameters

What do you think of this ?
I can implement the other approach if you think it is better

Best regards

### CODE REVIEW

**Comment by Sonic0** [comment]
Hey @JackSlateur, I'm glad to reread you! I'll watch this PR during the day and I'll try your example. I'm sorry for the delay.

**Review by Sonic0 — APPROVED** [review]

**Comment by Sonic0** [comment]
Thanks @JackSlateur for your contribution.
As mentioned in the other PRs, I no longer use this library and don't have time to maintain it. Therefore, I'm planning to archive this repository. 
After a review without local testing, I merged your code to publish the latest release. 
If you're interested, I can transfer ownership of this repository and the PyPI project to you. Please let me know.

**Comment by Sonic0** [comment]
@JackSlateur, I received your private message about the ownership transfer for this project. Was the message really from you or was it a scam?

**Comment by JackSlateur** [comment]
@Sonic0 Yes, it was me on keybase

**Pull request merged**
