### PR TITLE
Add batching support

### PR DESCRIPTION
**Pull request by JackSlateur**
Hello,

This is a batch of small changes we use in production
It adds batching support which, when enabled, allows the lib to bufferize events and not send an API calls every time send_data() is called

Thank you again for your very helpful work with this library

### CODE REVIEW

**Comment by Sonic0** [comment]
Thanks @JackSlateur, I really appreciate your PRs to this repo 🥰.
Could you please add a code example of the usage of this new feature (in the README) for other users who might want to use this library? Or you can share the example in this PR, and I'll include it in the documentation.

**Comment by JackSlateur** [comment]
Hello @Sonic0 
I've updated the README accordingly

To give extra context, we are using splunk-data-sender to transform a stream of events before sending them to Splunk: from s3 files, but also from syslog etc, so the stream is of arbitrary length

Best regards,

**Comment by Sonic0** [comment]
I'll try to reserve some time to test the code with a Splunk container tomorrow. If I can't, I'll proceed with merging the code directly.

**Review by Sonic0 — APPROVED** [review]

**Comment by JackSlateur** [comment]
Thank you for the merge, and for the pypi release too!

**Pull request merged**
